### ISSUE TITLE
missing META dir

### ISSUE THREAD

**Issue by royburner** [Sylvain78/Preuves#1]
Hi, i'm trying make install but get error :

make install
ocamlfind install prop META \
    _build/src/lib/prop.cmi \
    _build/src/lib/prop.cmo \
    _build/src/lib/prop.cmx \
    _build/src/lib/prop.a \
    _build/src/lib/prop.o \
    _build/src/lib/prop.cma \
    _build/src/lib/prop.cmxa \
    _build/src/lib/prop.cmxs
ocamlfind: META: No such file or directory
Makefile:65: recipe for target 'install' failed
make: **\* [install] Error 2

missing META dir on repo ?

**Comment by Sylvain78** [comment]
I will correct that this weekend. Thanks for your interest in my project !

**Comment by Sylvain78** [comment]
META file added. 
Not sure though its content is accurate.
