### ISSUE TITLE
Package bisect_ppx.fast is deprecated

### ISSUE THREAD

**Issue by aantron** [Sylvain78/Preuves#2]
There was actually no point in having fast/slow modes, as all were equally thread-safe, so we made them all fast (https://github.com/aantron/bisect_ppx/commit/dbe8a84879a80c07b899d76666522262b359fde8). We are planning to remove `bisect_ppx.fast` in https://github.com/aantron/bisect_ppx/issues/144, probably in a few months. You should use the regular `bisect_ppx` package instead.

Enjoy!

**Comment by Sylvain78** [comment]
Use of bisect_ppx.
